
project_id = "kwxsnkckyjkmpdzrsyxi"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions.create-payment-intent]
verify_jwt = true

[functions.confirm-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.manage-payment-methods]
verify_jwt = true

[functions.create-stripe-account]
verify_jwt = true

[functions.create-stripe-connect-account]
verify_jwt = true

[functions.process-creator-payout]
verify_jwt = true

[functions.check-stripe-account-status]
verify_jwt = true

[functions.generate-tax-report]
verify_jwt = true

[functions.request-instant-payout]
verify_jwt = true
